
server:
  port: 9021
logging:
  path: /com.twinkle.cloud.common.asm.def.var/log/micro/core/
  
ribbon:
  eureka:
    enabled: true


security:
  basic:
    enabled: false
  ignored: /noauth/**, /swagger**,/swagger**/**,/webjars/**,/v2/**, /js/**, /css/**, /sysdic/**
  oauth2:
    client:
      client-id: fox-service
      client-secret: secret
      access-token-uri:  http://${AUTHSERVER_SERVICE_HOST}:${AUTHSERVER_SERVICE_PORT}/uaa/oauth/token
      grant-type: client_credentials
    resource:
      token-info-uri: http://${AUTHSERVER_SERVICE_HOST}:${AUTHSERVER_SERVICE_PORT}/uaa/oauth/check_token

---
spring:
  profiles: cloud
  jpa:
    show-sql: false
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://192.168.1.252:3307/foxbase?useUnicode=true&amp;characterEncoding=utf8
    username: vaadin
    password: abcd1234
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  redis:
    database: 0
    host: 15.114.102.10
    port: 6379
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
  data:
    rest:
      default-page-size: 1000
eureka:
  client:
    serviceUrl:
      defaultZone: http://pro-discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
---
spring:
  profiles: development
  jpa:
    show-sql: false
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://172.16.33.7:3306/ts_user?useUnicode=true&amp;characterEncoding=utf8
    username: user_user
    password: 1qaz!QAZ
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  data:
    rest:
      default-page-size: 1000

  redis:
    port: 6379
    host: 172.16.33.232
    database: 0
    password: QAZwsx123!!
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 300
        max-idle: 8
        max-wait: 1000ms
  rabbitmq:
    host: 172.16.33.178
    port: 5672
    username: root
    password: QAZwsx123!!
    virtual-host: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.112.91:8761/eureka/
  instance:
    preferIpAddress: true
    
---
spring:
  profiles: test
  jpa:
    show-sql: false
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://15.114.102.7:3306/foxtest?useUnicode=true&amp;characterEncoding=utf8
    username: admin
    password: 1qaz!QAZ
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  redis:
    database: 11
    host: 15.114.102.10
    port: 6379
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
  data:
    rest:
      default-page-size: 1000
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://test-discovery:8761/eureka/
  instance:
    preferIpAddress: true

    
---
spring:
  profiles: local
  jpa:
    show-sql: false
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/yy-base?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  redis:
    database: 6
    host: 15.114.102.10
    port: 6379
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
  data:
    rest:
      default-page-size: 1000
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.112.91:8761/eureka/
  instance:
    preferIpAddress: true
    